/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        avatar4 = new javax.swing.JLabel();
        avatar1 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 239, 225));
        setMaximumSize(new java.awt.Dimension(943, 613));
        setMinimumSize(new java.awt.Dimension(943, 613));
        setPreferredSize(new java.awt.Dimension(943, 613));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseExited(evt);
            }
        });
        add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\UNO_Logo.svg (1) (1).png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 260, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecciona tu avatar:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre de Jugador:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        avatar4.setText("avatar 4");
        add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 70, 50));

        avatar1.setText("avatar 1");
        add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 70, 50));

        avatar2.setText("avatar 2");
        add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 70, 50));

        avatar3.setText("Avatar 3");
        add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 70, 50));

        BtnContinuar.setBackground(new java.awt.Color(255, 0, 0));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Continuar");
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 170, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_campoUsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
    public void listenerBtnContinuar(ActionListener listener){
        BtnContinuar.addActionListener(listener);
    }
}
